apiVersion: v1
kind: Service
metadata:
  labels:
    service: stateless-app-frontend
  name: stateless-app-frontend-svc
  namespace: stateless-app-ns
spec:
  type: NodePort
  ports:
    - name: "frontend-port"
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    service: stateless-app-frontend
