apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: praktikant-binding
  namespace: stateless-app-ns
subjects:
- kind: User
  name: moritz
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: praktikant
  apiGroup: rbac.authorization.k8s.io
