apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stateless-app-ns
  name: praktikant
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
