apiVersion: v1
kind: Service
metadata:
  labels:
    service: stateless-app-frontend
  name: stateless-app-frontend-svc
spec:
  ports:
    - name: "frontend-port"
      port: 80
      targetPort: 80
  selector:
    service: stateless-app-frontend
